export const JENIS_PERUSAHAAN = {
  UMUM: "umum",
  MANUFAKTUR: "manufaktur",
  // DAGANG: "dagang",
  JASA: "jasa",
};

export const BAGIAN_LAMPIRAN = {
  A: "A",
  B: "B",
  C: "C",
};

export const KODE_KOREKSI_OPTIONS = [
  { value: "", label: "" },
  {
    value: "FPO-01",
    label:
      "Fees charged/issued for the personal interest of the Taxpayer or his dependents",
  },
  {
    value: "FPO-02",
    label:
      "Health insurance premiums, accident insurance, life insurance, endowment insurance, and scholarship insurance paid by the taxpayer",
  },
  {
    value: "FPO-03",
    label:
      "Replacement or compensation for work or services in kind and enjoyment",
  },
  {
    value: "FPO-04",
    label:
      "Amounts that exceed the reasonable amount paid to related parties in connection with the work performed",
  },
  {
    value: "FPO-05",
    label: "Donated property, help or donation",
  },
  {
    value: "FPO-06",
    label: "Income Tax",
  },
  {
    value: "FPO-07",
    label: "Salary paid to the owner/person who is his dependents",
  },
  {
    value: "FPO-08",
    label: "Administrative sanctions",
  },
  {
    value: "FPO-09",
    label:
      "The difference between commercial depreciation over fiscal depreciation",
  },
  {
    value: "FPO-10",
    label:
      "The difference between commercial amortization over fiscal amortization",
  },
  {
    value: "FPO-11",
    label:
      "Fees for obtaining, collecting and maintaining income subject to Final Income Tax and income that is not included in the tax object",
  },
  {
    value: "FPO-12",
    label: "Another positive fiscal adjustment",
  },
  {
    value: "FNE-01",
    label:
      "Income that is subject to final income tax and income that is not included in the tax object but is included in the business cycle",
  },
  {
    value: "FNE-02",
    label:
      "The difference between commercial depreciation under fiscal depreciation",
  },
  {
    value: "FNE-03",
    label: "Amortization difference under fiscal amortization",
  },
  {
    value: "FNE-04",
    label: "Other negative fiscal adjustments",
  },
];

export const PERUSAHAAN_CONFIG = {
  [JENIS_PERUSAHAAN.UMUM]: {
    akunKonteks: {
      // Penjualan
      4002: ["umum"],
      4003: ["umum"],
      4004: ["umum"],
      // Penjualan Dikurangi
      4011: ["umum"],
      4012: ["umum"],
      4013: ["umum"],
      4020: ["umum"],
      // Harga Pokok Penjualan (HPP)
      5001: ["umum"],
      5003: ["umum"],
      5007: ["umum"],
      5008: ["umum"],
      5009: ["umum"],
      5020: ["umum"],
      4300: ["umum"],
      4199: ["umum"],
      // Beban Usaha
      5311: ["umum"],
      5312: ["umum"],
      5313: ["umum"],
      5314: ["umum"],
      5315: ["umum"],
      5316: ["umum"],
      5317: ["umum"],
      5318: ["umum"],
      5319: ["umum"],
      5320: ["umum"],
      5321: ["umum"],
      5322: ["umum"],
      5399: ["umum"],
      5400: ["umum"],
      4500: ["umum"],
      // Pendapatan Non Usaha
      4501: ["umum"],
      4503: ["umum"],
      4511: ["umum"],
      4599: ["umum"],
      4600: ["umum"],
      // Beban Non Usaha
      5405: ["umum"],
      5409: ["umum"],
      5421: ["umum"],
      5499: ["umum"],
      5500: ["umum"],
      4700: ["umum"],
      4800: ["umum"],
    },
    subtotalCalculations: {
      [BAGIAN_LAMPIRAN.A]: [
        "hitungSubtotal4004",
        "hitungSubtotal4020",
        "hitungSubtotal5020",
        "hitungSubtotal4300",
        "hitungSubtotal5400",
        "hitungSubtotal4500",
        "hitungSubtotal4600",
        "hitungSubtotal5500",
        "hitungTotal4700",
        "hitungTotal4800",
      ],
      [BAGIAN_LAMPIRAN.B]: [],
      [BAGIAN_LAMPIRAN.C]: [],
    },
    readOnlyFields: {
      4011: ["nonObjekPajak", "pphFinal"],
      4012: ["nonObjekPajak", "pphFinal"],
      4013: ["nonObjekPajak", "pphFinal"],
      5001: ["nonObjekPajak", "pphFinal"],
      5003: ["nonObjekPajak", "pphFinal"],
      5007: ["nonObjekPajak", "pphFinal"],
      5008: ["nonObjekPajak", "pphFinal"],
      5009: ["nonObjekPajak", "pphFinal"],
      5311: ["nonObjekPajak", "pphFinal"],
      5312: ["nonObjekPajak", "pphFinal"],
      5313: ["nonObjekPajak", "pphFinal"],
      5314: ["nonObjekPajak", "pphFinal"],
      5315: ["nonObjekPajak", "pphFinal"],
      5316: ["nonObjekPajak", "pphFinal"],
      5317: ["nonObjekPajak", "pphFinal"],
      5318: ["nonObjekPajak", "pphFinal"],
      5319: ["nonObjekPajak", "pphFinal"],
      5320: ["nonObjekPajak", "pphFinal"],
      5321: ["nonObjekPajak", "pphFinal"],
      5399: ["nonObjekPajak", "pphFinal"],
      5405: ["nonObjekPajak", "pphFinal"],
      5409: ["nonObjekPajak", "pphFinal"],
      5421: ["nonObjekPajak", "pphFinal"],
      5499: ["nonObjekPajak", "pphFinal"],
    },
  },

  [JENIS_PERUSAHAAN.MANUFAKTUR]: {
    akunKonteks: {
      // Penjualan
      4002: ["manufaktur"],
      4003: ["manufaktur"],
      4004: ["manufaktur"],
      // Penjualan Dikurangi
      4011: ["manufaktur"],
      4012: ["manufaktur"],
      4013: ["manufaktur"],
      4020: ["manufaktur"],
      // Harga Pokok Produksi
      5021: ["manufaktur"],
      5022: ["manufaktur"],
      5029: ["manufaktur"],
      5030: ["manufaktur"],
      5031: ["manufaktur"],
      5032: ["manufaktur"],
      5040: ["manufaktur"],
      5050: ["manufaktur"],
      // Biaya Pabrikasi
      5051: ["manufaktur"],
      5052: ["manufaktur"],
      5058: ["manufaktur"],
      5059: ["manufaktur"],
      5069: ["manufaktur"],
      5070: ["manufaktur"],
      5080: ["manufaktur"],
      5090: ["manufaktur"],
      5099: ["manufaktur"],
      5100: ["manufaktur"],
      5008: ["manufaktur"],
      5009: ["manufaktur"],
      5020: ["manufaktur"],
      4300: ["manufaktur"],
      4199: ["manufaktur"],
      // Beban Usaha
      5311: ["manufaktur"],
      5312: ["manufaktur"],
      5313: ["manufaktur"],
      5314: ["manufaktur"],
      5315: ["manufaktur"],
      5316: ["manufaktur"],
      5317: ["manufaktur"],
      5318: ["manufaktur"],
      5319: ["manufaktur"],
      5320: ["manufaktur"],
      5321: ["manufaktur"],
      5322: ["manufaktur"],
      5399: ["manufaktur"],
      5400: ["manufaktur"],
      4500: ["manufaktur"],
      // Pendapatan Non Usaha
      4501: ["manufaktur"],
      4503: ["manufaktur"],
      4511: ["manufaktur"],
      4599: ["manufaktur"],
      4600: ["manufaktur"],
      // Beban Non Usaha
      5405: ["manufaktur"],
      5409: ["manufaktur"],
      5421: ["manufaktur"],
      5499: ["manufaktur"],
      5500: ["manufaktur"],
      4700: ["manufaktur"],
      4800: ["manufaktur"],
    },
    subtotalCalculations: {
      [BAGIAN_LAMPIRAN.A]: [
        "hitungSubtotal4004",
        "hitungSubtotal4020",
        "hitungSubtotal5020",
        "hitungSubtotal5030",
        "hitungSubtotal5040",
        "hitungSubtotal5070",
        "hitungSubtotal5080",
        "hitungSubtotal5100",
        "hitungSubtotal4300",
        "hitungSubtotal5400",
        "hitungSubtotal4500",
        "hitungSubtotal4600",
        "hitungSubtotal5500",
        "hitungTotal4700",
        "hitungTotal4800",
      ],
      [BAGIAN_LAMPIRAN.B]: [],
      [BAGIAN_LAMPIRAN.C]: [],
    },
    readOnlyFields: {
      4011: ["nonObjekPajak", "pphFinal"],
      4012: ["nonObjekPajak", "pphFinal"],
      4013: ["nonObjekPajak", "pphFinal"],
      5008: ["nonObjekPajak", "pphFinal"],
      5009: ["nonObjekPajak", "pphFinal"],
      5311: ["nonObjekPajak", "pphFinal"],
      5312: ["nonObjekPajak", "pphFinal"],
      5313: ["nonObjekPajak", "pphFinal"],
      5314: ["nonObjekPajak", "pphFinal"],
      5315: ["nonObjekPajak", "pphFinal"],
      5316: ["nonObjekPajak", "pphFinal"],
      5317: ["nonObjekPajak", "pphFinal"],
      5318: ["nonObjekPajak", "pphFinal"],
      5319: ["nonObjekPajak", "pphFinal"],
      5320: ["nonObjekPajak", "pphFinal"],
      5321: ["nonObjekPajak", "pphFinal"],
      5399: ["nonObjekPajak", "pphFinal"],
      5405: ["nonObjekPajak", "pphFinal"],
      5409: ["nonObjekPajak", "pphFinal"],
      5421: ["nonObjekPajak", "pphFinal"],
      5499: ["nonObjekPajak", "pphFinal"],
    },
  },

  [JENIS_PERUSAHAAN.JASA]: {
    akunKonteks: {
      // Pendapatan
      4021: ["jasa"],
      4013: ["jasa"],
      5020: ["jasa"],
      4300: ["jasa"],
      4199: ["jasa"],
      //Beban
      5311: ["jasa"],
      5312: ["jasa"],
      5313: ["jasa"],
      5314: ["jasa"],
      5315: ["jasa"],
      5316: ["jasa"],
      5317: ["jasa"],
      5318: ["jasa"],
      5319: ["jasa"],
      5320: ["jasa"],
      5321: ["jasa"],
      5399: ["jasa"],
      5400: ["jasa"],
      4500: ["jasa"],
      // Pendapatan Non Usaha
      4501: ["jasa"],
      4503: ["jasa"],
      4511: ["jasa"],
      4599: ["jasa"],
      4600: ["jasa"],
      // Beban Non Usaha
      5405: ["jasa"],
      5409: ["jasa"],
      5421: ["jasa"],
      5499: ["jasa"],
      5500: ["jasa"],
      4700: ["jasa"],
      4800: ["jasa"],
    },
    subtotalCalculations: {
      [BAGIAN_LAMPIRAN.A]: [
        "hitungSubtotal4300",
        "hitungSubtotal5400",
        "hitungSubtotal4500",
        "hitungSubtotal4600",
        "hitungSubtotal5500",
        "hitungTotal4700",
        "hitungTotal4800",
      ],
      [BAGIAN_LAMPIRAN.B]: [],
      [BAGIAN_LAMPIRAN.C]: [],
    },
    readOnlyFields: {
      44013: ["nonObjekPajak", "pphFinal"],
      5020: ["nonObjekPajak", "pphFinal"],
      5311: ["nonObjekPajak", "pphFinal"],
      5312: ["nonObjekPajak", "pphFinal"],
      5313: ["nonObjekPajak", "pphFinal"],
      5314: ["nonObjekPajak", "pphFinal"],
      5315: ["nonObjekPajak", "pphFinal"],
      5316: ["nonObjekPajak", "pphFinal"],
      5317: ["nonObjekPajak", "pphFinal"],
      5318: ["nonObjekPajak", "pphFinal"],
      5319: ["nonObjekPajak", "pphFinal"],
      5320: ["nonObjekPajak", "pphFinal"],
      5321: ["nonObjekPajak", "pphFinal"],
      5399: ["nonObjekPajak", "pphFinal"],
      4599: ["penyesuaianPositif", "penyesuaianNegatif", "kodePenyesuaian"],
      5405: ["nonObjekPajak", "pphFinal"],
      5409: ["nonObjekPajak", "pphFinal"],
      5421: ["nonObjekPajak", "pphFinal"],
      5499: ["nonObjekPajak", "pphFinal"],
    },
  },
};
