export const JENIS_PERUSAHAAN = {
  UMUM: "umum",
  MANUFAKTUR: "manufaktur",
  DAGANG: "dagang",
  JASA: "jasa",
  BANK_KONVENSIONAL: "bank_konvensional",
  DANA_PENSIUN: "dana_pensiun",
  ASURANSI: "asuransi",
  PROPERTI: "properti",
  BANK_SYARIAH: "bank_syariah",
};

export const BAGIAN_LAMPIRAN = {
  A: "A",
  B: "B",
  C: "C",
};

export const KODE_KOREKSI_OPTIONS = [
  { value: "", label: "" },
  {
    value: "FPO-01",
    label: "Fees charged/issued for the personal interest of the Taxpayer or his dependents",
  },
  {
    value: "FPO-02",
    label:
      "Health insurance premiums, accident insurance, life insurance, endowment insurance, and scholarship insurance paid by the taxpayer",
  },
  {
    value: "FPO-03",
    label: "Replacement or compensation for work or services in kind and enjoyment",
  },
  {
    value: "FPO-04",
    label:
      "Amounts that exceed the reasonable amount paid to related parties in connection with the work performed",
  },
  {
    value: "FPO-05",
    label: "Donated property, help or donation",
  },
  {
    value: "FPO-06",
    label: "Income Tax",
  },
  {
    value: "FPO-07",
    label: "Salary paid to the owner/person who is his dependents",
  },
  {
    value: "FPO-08",
    label: "Administrative sanctions",
  },
  {
    value: "FPO-09",
    label: "The difference between commercial depreciation over fiscal depreciation",
  },
  {
    value: "FPO-10",
    label: "The difference between commercial amortization over fiscal amortization",
  },
  {
    value: "FPO-11",
    label:
      "Fees for obtaining, collecting and maintaining income subject to Final Income Tax and income that is not included in the tax object",
  },
  {
    value: "FPO-12",
    label: "Another positive fiscal adjustment",
  },
  {
    value: "FNE-01",
    label:
      "Income that is subject to final income tax and income that is not included in the tax object but is included in the business cycle",
  },
  {
    value: "FNE-02",
    label: "The difference between commercial depreciation under fiscal depreciation",
  },
  {
    value: "FNE-03",
    label: "Amortization difference under fiscal amortization",
  },
  {
    value: "FNE-04",
    label: "Other negative fiscal adjustments",
  },
];

export const PERUSAHAAN_CONFIG = {
  [JENIS_PERUSAHAAN.UMUM]: {
    akunKonteks: {
      // Penjualan
      4002: ["umum"],
      4003: ["umum"],
      4004: ["umum"],
      // Penjualan Dikurangi
      4011: ["umum"],
      4012: ["umum"],
      4013: ["umum"],
      4020: ["umum"],
      // Harga Pokok Penjualan (HPP)
      5001: ["umum"],
      5003: ["umum"],
      5007: ["umum"],
      5008: ["umum"],
      5009: ["umum"],
      5020: ["umum"],
      4300: ["umum"],
      4199: ["umum"],
      // Beban Usaha
      5311: ["umum"],
      5312: ["umum"],
      5313: ["umum"],
      5314: ["umum"],
      5315: ["umum"],
      5316: ["umum"],
      5317: ["umum"],
      5318: ["umum"],
      5319: ["umum"],
      5320: ["umum"],
      5321: ["umum"],
      5322: ["umum"],
      5399: ["umum"],
      5400: ["umum"],
      4500: ["umum"],
      // Pendapatan Non Usaha
      4501: ["umum"],
      4503: ["umum"],
      4511: ["umum"],
      4599: ["umum"],
      4600: ["umum"],
      // Beban Non Usaha
      5405: ["umum"],
      5409: ["umum"],
      5421: ["umum"],
      5499: ["umum"],
      5500: ["umum"],
      4700: ["umum"],
      4800: ["umum"],
    },
    subtotalCalculations: {
      [BAGIAN_LAMPIRAN.A]: [
        "hitungSubtotal4004",
        "hitungSubtotal4020",
        "hitungSubtotal5020",
        "hitungSubtotal4300",
        "hitungSubtotal5400",
        "hitungSubtotal4500",
        "hitungSubtotal4600",
        "hitungSubtotal5500",
        "hitungTotal4700",
        "hitungTotal4800",
      ],
      [BAGIAN_LAMPIRAN.B]: [],
      [BAGIAN_LAMPIRAN.C]: [],
    },
    readOnlyFields: {
      4011: ["nonObjekPajak", "pphFinal"],
      4012: ["nonObjekPajak", "pphFinal"],
      4013: ["nonObjekPajak", "pphFinal"],
      5001: ["nonObjekPajak", "pphFinal"],
      5003: ["nonObjekPajak", "pphFinal"],
      5007: ["nonObjekPajak", "pphFinal"],
      5008: ["nonObjekPajak", "pphFinal"],
      5009: ["nonObjekPajak", "pphFinal"],
      5311: ["nonObjekPajak", "pphFinal"],
      5312: ["nonObjekPajak", "pphFinal"],
      5313: ["nonObjekPajak", "pphFinal"],
      5314: ["nonObjekPajak", "pphFinal"],
      5315: ["nonObjekPajak", "pphFinal"],
      5316: ["nonObjekPajak", "pphFinal"],
      5317: ["nonObjekPajak", "pphFinal"],
      5318: ["nonObjekPajak", "pphFinal"],
      5319: ["nonObjekPajak", "pphFinal"],
      5320: ["nonObjekPajak", "pphFinal"],
      5321: ["nonObjekPajak", "pphFinal"],
      5399: ["nonObjekPajak", "pphFinal"],
      5405: ["nonObjekPajak", "pphFinal"],
      5409: ["nonObjekPajak", "pphFinal"],
      5421: ["nonObjekPajak", "pphFinal"],
      5499: ["nonObjekPajak", "pphFinal"],
    },
  },

  [JENIS_PERUSAHAAN.MANUFAKTUR]: {
    akunKonteks: {
      // Penjualan
      4002: ["manufaktur"],
      4003: ["manufaktur"],
      4004: ["manufaktur"],
      // Penjualan Dikurangi
      4011: ["manufaktur"],
      4012: ["manufaktur"],
      4013: ["manufaktur"],
      4020: ["manufaktur"],
      // Harga Pokok Produksi
      5021: ["manufaktur"],
      5022: ["manufaktur"],
      5029: ["manufaktur"],
      5030: ["manufaktur"],
      5031: ["manufaktur"],
      5032: ["manufaktur"],
      5040: ["manufaktur"],
      5050: ["manufaktur"],
      // Biaya Pabrikasi
      5051: ["manufaktur"],
      5052: ["manufaktur"],
      5058: ["manufaktur"],
      5059: ["manufaktur"],
      5069: ["manufaktur"],
      5070: ["manufaktur"],
      5080: ["manufaktur"],
      5090: ["manufaktur"],
      5099: ["manufaktur"],
      5100: ["manufaktur"],
      5008: ["manufaktur"],
      5009: ["manufaktur"],
      5020: ["manufaktur"],
      4300: ["manufaktur"],
      4199: ["manufaktur"],
      // Beban Usaha
      5311: ["manufaktur"],
      5312: ["manufaktur"],
      5313: ["manufaktur"],
      5314: ["manufaktur"],
      5315: ["manufaktur"],
      5316: ["manufaktur"],
      5317: ["manufaktur"],
      5318: ["manufaktur"],
      5319: ["manufaktur"],
      5320: ["manufaktur"],
      5321: ["manufaktur"],
      5322: ["manufaktur"],
      5399: ["manufaktur"],
      5400: ["manufaktur"],
      4500: ["manufaktur"],
      // Pendapatan Non Usaha
      4501: ["manufaktur"],
      4503: ["manufaktur"],
      4511: ["manufaktur"],
      4599: ["manufaktur"],
      4600: ["manufaktur"],
      // Beban Non Usaha
      5405: ["manufaktur"],
      5409: ["manufaktur"],
      5421: ["manufaktur"],
      5499: ["manufaktur"],
      5500: ["manufaktur"],
      4700: ["manufaktur"],
      4800: ["manufaktur"],
    },
    subtotalCalculations: {
      [BAGIAN_LAMPIRAN.A]: [
        "hitungSubtotal4004",
        "hitungSubtotal4020",
        "hitungSubtotal5020",
        "hitungSubtotal5030",
        "hitungSubtotal5040",
        "hitungSubtotal5070",
        "hitungSubtotal5080",
        "hitungSubtotal5100",
        "hitungSubtotal4300",
        "hitungSubtotal5400",
        "hitungSubtotal4500",
        "hitungSubtotal4600",
        "hitungSubtotal5500",
        "hitungTotal4700",
        "hitungTotal4800",
      ],
      [BAGIAN_LAMPIRAN.B]: [],
      [BAGIAN_LAMPIRAN.C]: [],
    },
    readOnlyFields: {
      4011: ["nonObjekPajak", "pphFinal"],
      4012: ["nonObjekPajak", "pphFinal"],
      4013: ["nonObjekPajak", "pphFinal"],
      5008: ["nonObjekPajak", "pphFinal"],
      5009: ["nonObjekPajak", "pphFinal"],
      5311: ["nonObjekPajak", "pphFinal"],
      5312: ["nonObjekPajak", "pphFinal"],
      5313: ["nonObjekPajak", "pphFinal"],
      5314: ["nonObjekPajak", "pphFinal"],
      5315: ["nonObjekPajak", "pphFinal"],
      5316: ["nonObjekPajak", "pphFinal"],
      5317: ["nonObjekPajak", "pphFinal"],
      5318: ["nonObjekPajak", "pphFinal"],
      5319: ["nonObjekPajak", "pphFinal"],
      5320: ["nonObjekPajak", "pphFinal"],
      5321: ["nonObjekPajak", "pphFinal"],
      5399: ["nonObjekPajak", "pphFinal"],
      5405: ["nonObjekPajak", "pphFinal"],
      5409: ["nonObjekPajak", "pphFinal"],
      5421: ["nonObjekPajak", "pphFinal"],
      5499: ["nonObjekPajak", "pphFinal"],
    },
  },

  [JENIS_PERUSAHAAN.DAGANG]: {
    akunKonteks: {
      // Penjualan
      4002: ["dagang"],
      4003: ["dagang"],
      4004: ["dagang"],

      //Dikuarngi
      4011: ["dagang"],
      4012: ["dagang"],
      4013: ["dagang"],
      4020: ["dagang"],

      // Harga Pokok Penjualan (HPP)
      5001: ["dagang"],
      5003: ["dagang"],
      5007: ["dagang"],
      5008: ["dagang"],
      5009: ["dagang"],
      5020: ["dagang"],
      4300: ["dagang"],
      4199: ["dagang"],
      // Beban Usaha
      5311: ["dagang"],
      5312: ["dagang"],
      5313: ["dagang"],
      5314: ["dagang"],
      5315: ["dagang"],
      5316: ["dagang"],
      5317: ["dagang"],
      5318: ["dagang"],
      5319: ["dagang"],
      5320: ["dagang"],
      5321: ["dagang"],
      5322: ["dagang"],
      5399: ["dagang"],
      5400: ["dagang"],
      4500: ["dagang"],
      // Pendapatan Non Usaha
      4501: ["dagang"],
      4503: ["dagang"],
      4511: ["dagang"],
      4599: ["dagang"],
      4600: ["dagang"],
      // Beban Non Usaha
      5405: ["dagang"],
      5409: ["dagang"],
      5421: ["dagang"],
      5499: ["dagang"],
      5500: ["dagang"],
      4700: ["dagang"],
      4800: ["dagang"],
    },
    subtotalCalculations: {
      [BAGIAN_LAMPIRAN.A]: [
        "hitungSubtotal4004",
        "hitungSubtotal4020",
        "hitungSubtotal5020",
        "hitungSubtotal4300",
        "hitungSubtotal5400",
        "hitungSubtotal4500",
        "hitungSubtotal4600",
        "hitungSubtotal5500",
        "hitungTotal4700",
        "hitungTotal4800",
      ],
      [BAGIAN_LAMPIRAN.B]: [],
      [BAGIAN_LAMPIRAN.C]: [],
    },
    readOnlyFields: {
      4011: ["nonObjekPajak", "pphFinal"],
      4012: ["nonObjekPajak", "pphFinal"],
      4013: ["nonObjekPajak", "pphFinal"],
      5001: ["nonObjekPajak", "pphFinal"],
      5003: ["nonObjekPajak", "pphFinal"],
      5007: ["nonObjekPajak", "pphFinal"],
      5008: ["nonObjekPajak", "pphFinal"],
      5009: ["nonObjekPajak", "pphFinal"],

      5311: ["nonObjekPajak", "pphFinal"],
      5312: ["nonObjekPajak", "pphFinal"],
      5313: ["nonObjekPajak", "pphFinal"],
      5314: ["nonObjekPajak", "pphFinal"],
      5315: ["nonObjekPajak", "pphFinal"],
      5316: ["nonObjekPajak", "pphFinal"],
      5317: ["nonObjekPajak", "pphFinal"],
      5318: ["nonObjekPajak", "pphFinal"],
      5319: ["nonObjekPajak", "pphFinal"],
      5320: ["nonObjekPajak", "pphFinal"],
      5321: ["nonObjekPajak", "pphFinal"],
      5399: ["nonObjekPajak", "pphFinal"],
      4599: ["penyesuaianPositif", "penyesuaianNegatif", "kodePenyesuaian"],
      5405: ["nonObjekPajak", "pphFinal"],
      5409: ["nonObjekPajak", "pphFinal"],
      5421: ["nonObjekPajak", "pphFinal"],
      5499: ["nonObjekPajak", "pphFinal"],
    },
  },

  [JENIS_PERUSAHAAN.JASA]: {
    akunKonteks: {
      // Pendapatan
      4021: ["jasa"],
      4013: ["jasa"],
      5020: ["jasa"],
      4300: ["jasa"],
      4199: ["jasa"],
      //Beban
      5311: ["jasa"],
      5312: ["jasa"],
      5313: ["jasa"],
      5314: ["jasa"],
      5315: ["jasa"],
      5316: ["jasa"],
      5317: ["jasa"],
      5318: ["jasa"],
      5319: ["jasa"],
      5320: ["jasa"],
      5321: ["jasa"],
      5399: ["jasa"],
      5400: ["jasa"],
      4500: ["jasa"],
      // Pendapatan Non Usaha
      4501: ["jasa"],
      4503: ["jasa"],
      4511: ["jasa"],
      4599: ["jasa"],
      4600: ["jasa"],
      // Beban Non Usaha
      5405: ["jasa"],
      5409: ["jasa"],
      5421: ["jasa"],
      5499: ["jasa"],
      5500: ["jasa"],
      4700: ["jasa"],
      4800: ["jasa"],
    },
    subtotalCalculations: {
      [BAGIAN_LAMPIRAN.A]: [
        "hitungSubtotal4300",
        "hitungSubtotal5400",
        "hitungSubtotal4500",
        "hitungSubtotal4600",
        "hitungSubtotal5500",
        "hitungTotal4700",
        "hitungTotal4800",
      ],
      [BAGIAN_LAMPIRAN.B]: [],
      [BAGIAN_LAMPIRAN.C]: [],
    },
    readOnlyFields: {
      4013: ["nonObjekPajak", "pphFinal"],
      5020: ["nonObjekPajak", "pphFinal"],
      5311: ["nonObjekPajak", "pphFinal"],
      5312: ["nonObjekPajak", "pphFinal"],
      5313: ["nonObjekPajak", "pphFinal"],
      5314: ["nonObjekPajak", "pphFinal"],
      5315: ["nonObjekPajak", "pphFinal"],
      5316: ["nonObjekPajak", "pphFinal"],
      5317: ["nonObjekPajak", "pphFinal"],
      5318: ["nonObjekPajak", "pphFinal"],
      5319: ["nonObjekPajak", "pphFinal"],
      5320: ["nonObjekPajak", "pphFinal"],
      5321: ["nonObjekPajak", "pphFinal"],
      5399: ["nonObjekPajak", "pphFinal"],
      4599: ["penyesuaianPositif", "penyesuaianNegatif", "kodePenyesuaian"],
      5405: ["nonObjekPajak", "pphFinal"],
      5409: ["nonObjekPajak", "pphFinal"],
      5421: ["nonObjekPajak", "pphFinal"],
      5499: ["nonObjekPajak", "pphFinal"],
    },
  },

  [JENIS_PERUSAHAAN.BANK_KONVENSIONAL]: {
    akunKonteks: {
      // Pendapatan Bunga
      4027: ["bank_konvensional"],
      4028: ["bank_konvensional"],

      // Beban Bunga

      4031: ["bank_konvensional"],
      4033: ["bank_konvensional"],
      4040: ["bank_konvensional"],

      // Pendapatan Operasional Lain

      4071: ["bank_konvensional"],
      4072: ["bank_konvensional"],
      4073: ["bank_konvensional"],
      4074: ["bank_konvensional"],
      4091: ["bank_konvensional"],
      4092: ["bank_konvensional"],
      4093: ["bank_konvensional"],
      4094: ["bank_konvensional"],
      4199: ["bank_konvensional"],
      4210: ["bank_konvensional"],

      // beban Operasional Lain

      5350: ["bank_konvensional"],
      5351: ["bank_konvensional"],
      5352: ["bank_konvensional"],
      5353: ["bank_konvensional"],
      5354: ["bank_konvensional"],
      5346: ["bank_konvensional"],
      5356: ["bank_konvensional"],
      5348: ["bank_konvensional"],
      5358: ["bank_konvensional"],
      5311: ["bank_konvensional"],
      5312: ["bank_konvensional"],
      5313: ["bank_konvensional"],
      5314: ["bank_konvensional"],
      5315: ["bank_konvensional"],
      5316: ["bank_konvensional"],
      5317: ["bank_konvensional"],
      5318: ["bank_konvensional"],
      5320: ["bank_konvensional"],
      5321: ["bank_konvensional"],
      5322: ["bank_konvensional"],
      5399: ["bank_konvensional"],
      5401: ["bank_konvensional"],
      4400: ["bank_konvensional"],
      4600: ["bank_konvensional"],
      5500: ["bank_konvensional"],
      4700: ["bank_konvensional"],
      4800: ["bank_konvensional"],
    },
    subtotalCalculations: {
      [BAGIAN_LAMPIRAN.A]: [
        "hitungSubtotal4040",
        "hitungSubtotal4210",
        "hitungSubtotal5401",
        "hitungSubtotal4400",
        "hitungSubtotal4700",
        "hitungSubtotal4800",
      ],
      [BAGIAN_LAMPIRAN.B]: [],
      [BAGIAN_LAMPIRAN.C]: [],
    },
    readOnlyFields: {
      4031: ["nonObjekPajak", "pphFinal"],
      4033: ["nonObjekPajak", "pphFinal"],

      5350: ["nonObjekPajak", "pphFinal"],
      5351: ["nonObjekPajak", "pphFinal"],
      5352: ["nonObjekPajak", "pphFinal"],
      5353: ["nonObjekPajak", "pphFinal"],
      5354: ["nonObjekPajak", "pphFinal"],
      5346: ["nonObjekPajak", "pphFinal"],
      5356: ["nonObjekPajak", "pphFinal"],
      5348: ["nonObjekPajak", "pphFinal"],
      5358: ["nonObjekPajak", "pphFinal"],
      5311: ["nonObjekPajak", "pphFinal"],
      5312: ["nonObjekPajak", "pphFinal"],
      5313: ["nonObjekPajak", "pphFinal"],
      5314: ["nonObjekPajak", "pphFinal"],
      5315: ["nonObjekPajak", "pphFinal"],
      5316: ["nonObjekPajak", "pphFinal"],
      5317: ["nonObjekPajak", "pphFinal"],
      5318: ["nonObjekPajak", "pphFinal"],
      5320: ["nonObjekPajak", "pphFinal"],
      5321: ["nonObjekPajak", "pphFinal"],
      5322: ["nonObjekPajak", "pphFinal"],
      5399: ["nonObjekPajak", "pphFinal"],
      5500: ["nonObjekPajak", "pphFinal"],
    },
  },

  [JENIS_PERUSAHAAN.DANA_PENSIUN]: {
    akunKonteks: {
      // Pendapatan Investasi
      4026: ["dana_pensiun"],
      4091: ["dana_pensiun"],
      4101: ["dana_pensiun"],
      4106: ["dana_pensiun"],
      4118: ["dana_pensiun"],
      4120: ["dana_pensiun"],

      // Jumlah Pendapatan Investasi

      5201: ["dana_pensiun"],
      5202: ["dana_pensiun"],
      5203: ["dana_pensiun"],
      5204: ["dana_pensiun"],
      5205: ["dana_pensiun"],
      5299: ["dana_pensiun"],
      5300: ["dana_pensiun"],
      4300: ["dana_pensiun"],

      // Beban Operasional

      5311: ["dana_pensiun"],
      5312: ["dana_pensiun"],
      5323: ["dana_pensiun"],
      5326: ["dana_pensiun"],
      5314: ["dana_pensiun"],
      5316: ["dana_pensiun"],
      5317: ["dana_pensiun"],
      5318: ["dana_pensiun"],
      5320: ["dana_pensiun"],
      5399: ["dana_pensiun"],
      5400: ["dana_pensiun"],

      // Laba Rugi Non Operasional

      4512: ["dana_pensiun"],
      4513: ["dana_pensiun"],
      4514: ["dana_pensiun"],
      4599: ["dana_pensiun"],
      5499: ["dana_pensiun"],
      4700: ["dana_pensiun"],
      4800: ["dana_pensiun"],
    },

    subtotalCalculations: {
      [BAGIAN_LAMPIRAN.A]: [
        "hitungSubtotal4120",
        "hitungSubtotal5300",
        "hitungSubtotal4300",
        "hitungSubtotal5400",
        "hitungTotal4700",
        "hitungTotal4800",
      ],
      [BAGIAN_LAMPIRAN.B]: [],
      [BAGIAN_LAMPIRAN.C]: [],
    },
    readOnlyFields: {
      5201: ["nonObjekPajak", "pphFinal"],
      5202: ["nonObjekPajak", "pphFinal"],
      5203: ["nonObjekPajak", "pphFinal"],
      5204: ["nonObjekPajak", "pphFinal"],
      5205: ["nonObjekPajak", "pphFinal"],
      5299: ["nonObjekPajak", "pphFinal"],

      5311: ["nonObjekPajak", "pphFinal"],
      5312: ["nonObjekPajak", "pphFinal"],
      5323: ["nonObjekPajak", "pphFinal"],
      5326: ["nonObjekPajak", "pphFinal"],
      5314: ["nonObjekPajak", "pphFinal"],
      5316: ["nonObjekPajak", "pphFinal"],
      5317: ["nonObjekPajak", "pphFinal"],
      5318: ["nonObjekPajak", "pphFinal"],
      5320: ["nonObjekPajak", "pphFinal"],
      5399: ["nonObjekPajak", "pphFinal"],

      5499: ["nonObjekPajak", "pphFinal"],
    },
  },

  [JENIS_PERUSAHAAN.ASURANSI]: {
    akunKonteks: {
      4041: ["asuransi"],
      4045: ["asuransi"],
      4047: ["asuransi"],
      4051: ["asuransi"],
      4060: ["asuransi"],
      4171: ["asuransi"],
      4200: ["asuransi"],

      // Beban UnderWriting

      5101: ["asuransi"],
      5102: ["asuransi"],
      5103: ["asuransi"],
      5109: ["asuransi"],
      5200: ["asuransi"],
      4300: ["asuransi"],
      4120: ["asuransi"],
      4199: ["asuransi"],

      // Beban Operasional

      5311: ["asuransi"],
      5312: ["asuransi"],
      5313: ["asuransi"],
      5314: ["asuransi"],
      5315: ["asuransi"],
      5316: ["asuransi"],
      5317: ["asuransi"],
      5318: ["asuransi"],
      5319: ["asuransi"],
      5320: ["asuransi"],
      5321: ["asuransi"],
      5399: ["asuransi"],
      5400: ["asuransi"],
      4600: ["asuransi"],
      5500: ["asuransi"],
      4700: ["asuransi"],
      4800: ["asuransi"],
    },

    subtotalCalculations: {
      [BAGIAN_LAMPIRAN.A]: [
        "hitungSubtotal4060",
        "hitungSubtotal4200",
        "hitungSubtotal5200",
        "hitungSubtotal4300",
        "hitungSubtotal5400",
        "hitungTotal4700",
        "hitungTotal4800",
      ],
      [BAGIAN_LAMPIRAN.B]: [],
      [BAGIAN_LAMPIRAN.C]: [],
    },
    readOnlyFields: {
      4045: ["nonObjekPajak", "pphFinal"],
      4051: ["nonObjekPajak", "pphFinal"],
      4060: ["nonObjekPajak", "pphFinal"],
      5101: ["nonObjekPajak", "pphFinal"],
      5102: ["nonObjekPajak", "pphFinal"],
      5103: ["nonObjekPajak", "pphFinal"],
      5109: ["nonObjekPajak", "pphFinal"],
      5311: ["nonObjekPajak", "pphFinal"],
      5312: ["nonObjekPajak", "pphFinal"],
      5313: ["nonObjekPajak", "pphFinal"],
      5314: ["nonObjekPajak", "pphFinal"],
      5315: ["nonObjekPajak", "pphFinal"],
      5316: ["nonObjekPajak", "pphFinal"],
      5317: ["nonObjekPajak", "pphFinal"],
      5318: ["nonObjekPajak", "pphFinal"],
      5319: ["nonObjekPajak", "pphFinal"],
      5320: ["nonObjekPajak", "pphFinal"],
      5321: ["nonObjekPajak", "pphFinal"],
      5399: ["nonObjekPajak", "pphFinal"],
      5500: ["nonObjekPajak", "pphFinal"],
    },
  },

  [JENIS_PERUSAHAAN.PROPERTI]: {
    akunKonteks: {
      // Pendapatan Sewa
      4001: ["properti"],
      4013: ["properti"],
      4026: ["properti"],
      4101: ["properti"],
      4071: ["properti"],
      5020: ["properti"],
      4300: ["properti"],
      4153: ["properti"],
      4199: ["properti"],
      5324: ["properti"],

      // Beban Usaha

      5311: ["properti"],
      5312: ["properti"],
      5313: ["properti"],
      5314: ["properti"],
      5315: ["properti"],
      5316: ["properti"],
      5317: ["properti"],
      5318: ["properti"],
      5319: ["properti"],
      5320: ["properti"],
      5321: ["properti"],
      5322: ["properti"],
      5399: ["properti"],
      5400: ["properti"],
      4500: ["properti"],

      // Pendapatan Non Usaha

      4511: ["properti"],
      4501: ["properti"],
      4599: ["properti"],
      4600: ["properti"],

      // Beban Non Usaha

      5405: ["properti"],
      5409: ["properti"],
      5421: ["properti"],
      5499: ["properti"],
      5500: ["properti"],
      4700: ["properti"],
      4800: ["properti"],
    },

    subtotalCalculations: {
      [BAGIAN_LAMPIRAN.A]: [
        "hitungSubtotal4300",
        "hitungSubtotal5400",
        "hitungSubtotal4500",
        "hitungSubtotal4600",
        "hitungSubtotal5500",
        "hitungTotal4700",
        "hitungTotal4800",
      ],
      [BAGIAN_LAMPIRAN.B]: [],
      [BAGIAN_LAMPIRAN.C]: [],
    },
    readOnlyFields: {
      4013: ["nonObjekPajak", "pphFinal"],
      5020: ["nonObjekPajak", "pphFinal"],
      5324: ["nonObjekPajak", "pphFinal"],
      5311: ["nonObjekPajak", "pphFinal"],
      5312: ["nonObjekPajak", "pphFinal"],
      5313: ["nonObjekPajak", "pphFinal"],
      5314: ["nonObjekPajak", "pphFinal"],
      5315: ["nonObjekPajak", "pphFinal"],
      5316: ["nonObjekPajak", "pphFinal"],
      5317: ["nonObjekPajak", "pphFinal"],
      5318: ["nonObjekPajak", "pphFinal"],
      5319: ["nonObjekPajak", "pphFinal"],
      5320: ["nonObjekPajak", "pphFinal"],
      5321: ["nonObjekPajak", "pphFinal"],
      5322: ["nonObjekPajak", "pphFinal"],
      5399: ["nonObjekPajak", "pphFinal"],
      5399: ["nonObjekPajak", "pphFinal"],
      5405: ["nonObjekPajak", "pphFinal"],
      5409: ["nonObjekPajak", "pphFinal"],
      5421: ["nonObjekPajak", "pphFinal"],
      5499: ["nonObjekPajak", "pphFinal"],
    },
  },

  [JENIS_PERUSAHAAN.BANK_SYARIAH]: {
    akunKonteks: {
      // Pendapatan Dari Piutang
      4121: ["bank_syariah"],
      4122: ["bank_syariah"],
      4123: ["bank_syariah"],
      4130: ["bank_syariah"],

      // Pendapatan Bagi Hasil
      4131: ["bank_syariah"],
      4132: ["bank_syariah"],
      4140: ["bank_syariah"],
      4149: ["bank_syariah"],
      4150: ["bank_syariah"],

      // Bagi asil Untuk pemilik Dana Investasi

      5301: ["bank_syariah"],
      5302: ["bank_syariah"],
      5310: ["bank_syariah"],
      4300: ["bank_syariah"],

      // Pendapatan Operasional Lain

      4071: ["bank_syariah"],
      4073: ["bank_syariah"],
      4074: ["bank_syariah"],
      4084: ["bank_syariah"],
      4092: ["bank_syariah"],
      4091: ["bank_syariah"],
      4093: ["bank_syariah"],
      4094: ["bank_syariah"],
      4199: ["bank_syariah"],
      4210: ["bank_syariah"],

      // Beban Operasional Lain

      5341: ["bank_syariah"],
      5342: ["bank_syariah"],
      5343: ["bank_syariah"],
      5344: ["bank_syariah"],
      5345: ["bank_syariah"],
      5346: ["bank_syariah"],
      5347: ["bank_syariah"],
      5348: ["bank_syariah"],
      5349: ["bank_syariah"],
      5311: ["bank_syariah"],
      5313: ["bank_syariah"],
      5314: ["bank_syariah"],
      5315: ["bank_syariah"],
      5320: ["bank_syariah"],
      5321: ["bank_syariah"],
      5399: ["bank_syariah"],
      5401: ["bank_syariah"],
      4220: ["bank_syariah"],
      4500: ["bank_syariah"],

      // Pendapatan Non Operasional

      4501: ["bank_syariah"],
      4502: ["bank_syariah"],
      4599: ["bank_syariah"],

      // Beban Non Operasional

      5421: ["bank_syariah"],
      5422: ["bank_syariah"],
      5499: ["bank_syariah"],
      4700: ["bank_syariah"],
      4800: ["bank_syariah"],
    },

    subtotalCalculations: {
      [BAGIAN_LAMPIRAN.A]: [
        "hitungSubtotal4130",
        "hitungSubtotal4140",
        "hitungSubtotal4150",
        "hitungSubtotal5310",
        "hitungSubtotal4300",
        "hitungSubtotal4210",
        "hitungSubtotal5401",
        "hitungSubtotal4220",
        "hitungSubtotal4500",
        "hitungSubtotal4700",
        "hitungSubtotal4800",
      ],
      [BAGIAN_LAMPIRAN.B]: [],
      [BAGIAN_LAMPIRAN.C]: [],
    },
    readOnlyFields: {
      // 4013: ["nonObjekPajak", "pphFinal"],
      // 5020: ["nonObjekPajak", "pphFinal"],
      // 5324: ["nonObjekPajak", "pphFinal"],
      // 5311: ["nonObjekPajak", "pphFinal"],
      // 5312: ["nonObjekPajak", "pphFinal"],
      // 5313: ["nonObjekPajak", "pphFinal"],
      // 5314: ["nonObjekPajak", "pphFinal"],
      // 5315: ["nonObjekPajak", "pphFinal"],
      // 5316: ["nonObjekPajak", "pphFinal"],
      // 5317: ["nonObjekPajak", "pphFinal"],
      // 5318: ["nonObjekPajak", "pphFinal"],
      // 5319: ["nonObjekPajak", "pphFinal"],
      // 5320: ["nonObjekPajak", "pphFinal"],
      // 5321: ["nonObjekPajak", "pphFinal"],
      // 5322: ["nonObjekPajak", "pphFinal"],
      // 5399: ["nonObjekPajak", "pphFinal"],
      // 5399: ["nonObjekPajak", "pphFinal"],
      // 5405: ["nonObjekPajak", "pphFinal"],
      // 5409: ["nonObjekPajak", "pphFinal"],
      // 5421: ["nonObjekPajak", "pphFinal"],
      // 5499: ["nonObjekPajak", "pphFinal"],
    },
  },
};
