# ------------------- Stage 1: Build the Vue.js application ------------------ #
FROM node:22-alpine as build-stage

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# ----------------- Stage 2: Serve the application with Nginx ---------------- #
FROM nginx:stable-alpine as production-stage

# Set the working directory for Nginx
WORKDIR /usr/share/nginx/html

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

# Remove default Nginx static assets
RUN rm -rf ./*

# Copy the built assets from the build stage
COPY --from=build-stage /app/dist .

# Expose port 80
EXPOSE 80

# Start Nginx and keep it in the foreground
CMD ["nginx", "-g", "daemon off;"]
