// Dokumentasi cara menggunakan

// Untuk menampilkan semua Akun
//    ...pickByKode(["4002", "4003"]),

//  BARIS LINE PENTING
export const createLineRow = (akun, level = 0, options = {}) => ({
  id: akun.kodeAkun,
  type: "line",
  variant: options.variant ?? "normal",
  kodeAkun: akun.kodeAkun,
  keterangan: akun.namaAkun,
  level: akun.level ?? level,

  nilaiKomersial: 0,
  nonObjekPajak: 0,
  pphFinal: 0,
  tidakFinal: 0,
  penyesuaianPositif: 0,
  penyesuaianNegatif: 0,
  kodePenyesuaian: "",
  nilaiFiskal: 0,
});

export const MASTER_AKUN_LAPORAN_LABA_RUGI = [
  // AKUN MAKNA GANDA (BERDASARKAN JENIS PERUSAHAAN)
  {
    kodeAkun: "4001",
    jenisPerusahaan: ["manufaktur", "dagang"],
    namaAkun: "'Penjualan dan Pendapatan Usaha",
  },
  {
    kodeAkun: "4002",
    jenisPerusahaan: ["umum", "manufaktur", "dagang"],
    namaAkun: "Penjualan Domestik",
  },
  {
    kodeAkun: "4003",
    jenisPerusahaan: ["umum", "manufaktur", "dagang"],
    namaAkun: "Penjualan Expor",
  },
  {
    kodeAkun: "4004",
    jenisPerusahaan: ["umum", "manufaktur", "dagang"],
    namaAkun: "Penjualan Bruto",
  },
  {
    kodeAkun: "4011",
    jenisPerusahaan: ["umum", "manufaktur", "dagang"],
    namaAkun: "Retur",
  },
  {
    kodeAkun: "4012",
    jenisPerusahaan: ["umum", "manufaktur", "dagang"],
    namaAkun: "Potongan Penjualan",
  },
  {
    kodeAkun: "4013",
    jenisPerusahaan: ["umum", "manufaktur", "dagang", "jasa", "proeperti", "infrastruktur"],
    namaAkun: "Penyesuaian Penjualan",
  },
  {
    kodeAkun: "4020",
    jenisPerusahaan: ["umum", "dagang", "manufaktur"],
    namaAkun: "Penjualan Bersih",
  },
  {
    kodeAkun: "4021",
    namaAkun: "Pendapatan Jasa",
    jenisPerusahaan: ["jasa"],
  },
  {
    kodeAkun: "4026",
    namaAkun: "Bunga/Bagi Hasil",
    jenisPerusahaan: ["dana_pensiun"],
  },
  {
    kodeAkun: "4026",
    namaAkun: "Pendapatan Bunga (Komponen Pembiayaan pada Kontrak Pelanggan)",
    jenisPerusahaan: ["properti", "infrastruktur"],
  },
  {
    kodeAkun: "4026",
    namaAkun: "Pendapatan Bunga",
    jenisPerusahaan: ["sekuritas", "pembiayaan"],
  },
  {
    kodeAkun: "4027",
    namaAkun: "Pendapatan Bunga - Rupiah",
    jenisPerusahaan: ["bank_konvensional"],
  },
  {
    kodeAkun: "4028",
    namaAkun: "Pendapatan Bunga - Valuta Asing",
    jenisPerusahaan: ["bank_konvensional"],
  },
  {
    kodeAkun: "4031",
    namaAkun: "Beban Bunga - Rupiah",
    jenisPerusahaan: ["bank_konvensional"],
  },
  {
    kodeAkun: "4033",
    namaAkun: "Beban Bunga - Valuta Asing",
    jenisPerusahaan: ["bank_konvensional"],
  },
  {
    kodeAkun: "4040",
    namaAkun: "Pendapatan (Beban) Bunga Bersih",
    jenisPerusahaan: ["bank_konvensional"],
  },
  {
    kodeAkun: "4041",
    namaAkun: "Pendapatan Premi",
    jenisPerusahaan: ["asuransi"],
  },
  {
    kodeAkun: "4045",
    namaAkun: "Komisi Dibayar",
    jenisPerusahaan: ["asuransi"],
  },
  {
    kodeAkun: "4047",
    namaAkun: "Premi Reasuransi",
    jenisPerusahaan: ["asuransi"],
  },
  {
    kodeAkun: "4051",
    namaAkun: "Penurunan (Kenaikan) Cadangan Premi, CAPYBMP, dan Risiko Bencana",
    jenisPerusahaan: ["asuransi"],
  },
  {
    kodeAkun: "4060",
    namaAkun: "Jumlah Pendapatan Premi Neto",
    jenisPerusahaan: ["asuransi"],
  },
  {
    kodeAkun: "4061",
    namaAkun: "Pendapatan Bunga dari Pembiayaan Investasi",
    jenisPerusahaan: ["pembiayaan"],
  },
  {
    kodeAkun: "4062",
    namaAkun: "Pendapatan Bunga dari Pembiayaan Modal Kerja",
    jenisPerusahaan: ["pembiayaan"],
  },
  {
    kodeAkun: "4063",
    namaAkun: "Pendapatan Bunga dari Pembiayaan Multiguna",
    jenisPerusahaan: ["pembiayaan"],
  },
  {
    kodeAkun: "4064",
    namaAkun: "Pendapatan Bagi Hasil dari Kegiatan Pembiayaan Investasi (Prinsip Syariah)",
    jenisPerusahaan: ["pembiayaan"],
  },
  {
    kodeAkun: "4065",
    namaAkun: "Pendapatan Margin dari Kegiatan Pembiayaan Jual Beli (Prinsip Syariah)",
    jenisPerusahaan: ["pembiayaan"],
  },
  {
    kodeAkun: "4066",
    namaAkun: "Pendapatan Imbal Jasa dari Pembiayaan Jasa (Prinsip Syariah)",
    jenisPerusahaan: ["pembiayaan"],
  },
  {
    kodeAkun: "4071",
    namaAkun: "Keuntungan dari Peningkatan Nilai Wajar Aset Keuangan",
    jenisPerusahaan: ["bank_konvensional", "bank_syariah"],
  },
  {
    kodeAkun: "4071",
    namaAkun: "Keuntungan dari Peningkatan Nilai Wajar Aset",
    jenisPerusahaan: ["properti"],
  },
  {
    kodeAkun: "4072",
    namaAkun: "Keuntungan dari Penurunan Nilai Wajar Liabilitas Keuangan",
    jenisPerusahaan: ["bank_konvensional"],
  },
  {
    kodeAkun: "4073",
    namaAkun: "Keuntungan dari Penjualan Aset Keuangan",
    jenisPerusahaan: ["bank_konvensional"],
  },
  {
    kodeAkun: "4073",
    namaAkun: "Keuntungan Penjualan Aset (Surat Berharga dan Ijarah)",
    jenisPerusahaan: ["bank_syariah"],
  },
  {
    kodeAkun: "4074",
    namaAkun: "Keuntungan dari Transaksi Spot dan Derivatif",
    jenisPerusahaan: ["bank_konvensional"],
  },
  {
    kodeAkun: "4074",
    namaAkun: "Keuntungan Transaksi Spot dan Forward (Realized)",
    jenisPerusahaan: ["bank_syariah"],
  },
  {
    kodeAkun: "4081",
    namaAkun: "Pendapatan Kegiatan Perantara Perdagangan Efek",
    jenisPerusahaan: ["sekuritas"],
  },
  {
    kodeAkun: "4082",
    namaAkun: "Pendapatan Kegiatan Penjaminan Emisi Efek",
    jenisPerusahaan: ["sekuritas"],
  },
  {
    kodeAkun: "4083",
    namaAkun: "Pendapatan Kegiatan Manajer Investasi",
    jenisPerusahaan: ["sekuritas"],
  },
  {
    kodeAkun: "4084",
    namaAkun: "Pendapatan Bank Selaku Mudharib dalam Mudharabah Muqayyadah",
    jenisPerusahaan: ["pembiayaan"],
  },
  {
    kodeAkun: "4091",
    namaAkun: "Dividen",
    jenisPerusahaan: ["bank_konvensional", "dana_pensiun", "bank_syariah", "sekuritas"],
  },
  {
    kodeAkun: "4092",
    namaAkun: "Keuntungan dari Penyertaan dengan Equity Method",
    jenisPerusahaan: ["bank_konvensional", "bank_syariah"],
  },
  {
    kodeAkun: "4093",
    namaAkun: "Komisi/Provisi/Fee dan Administrasi",
    jenisPerusahaan: ["bank_konvensional", "bank_syariah"],
  },
  {
    kodeAkun: "4094",
    namaAkun: "Pemulihan atas Cadangan Kerugian Penurunan Nilai",
    jenisPerusahaan: ["bank_konvensional"],
  },
  {
    kodeAkun: "4094",
    namaAkun: "Pemulihan Penyisihan Kerugian Penurunan Nilai",
    jenisPerusahaan: ["bank_syariah"],
  },
  {
    kodeAkun: "4101",
    namaAkun: "Sewa",
    jenisPerusahaan: ["dana_pensiun"],
  },
  {
    kodeAkun: "4101",
    namaAkun: "Pendapatan Sewa",
    jenisPerusahaan: ["properti"],
  },
  {
    kodeAkun: "4106",
    namaAkun: "Laba (Rugi) Pelepasan Investasi",
    jenisPerusahaan: ["dana_pensiun"],
  },
  {
    kodeAkun: "4118",
    namaAkun: "Pendapatan Investasi Lain",
    jenisPerusahaan: ["dana_pensiun"],
  },
  {
    kodeAkun: "4120",
    namaAkun: "Jumlah Pendapatan Investasi",
    jenisPerusahaan: ["dana_pensiun"],
  },
  {
    kodeAkun: "4120",
    namaAkun: "Pendapatan Investasi",
    jenisPerusahaan: ["asuransi"],
  },
  {
    kodeAkun: "4121",
    namaAkun: "Murabaha",
    jenisPerusahaan: ["pembiayaan"],
  },
  {
    kodeAkun: "4122",
    namaAkun: "Istishna'",
    jenisPerusahaan: ["pembiayaan"],
  },
  {
    kodeAkun: "4123",
    namaAkun: "Ujrah",
    jenisPerusahaan: ["pembiayaan"],
  },
  {
    kodeAkun: "4130",
    namaAkun: "Total Pendapatan dari Piutang",
    jenisPerusahaan: ["pembiayaan"],
  },
  {
    kodeAkun: "4131",
    namaAkun: "Mudharabah",
    jenisPerusahaan: ["pembiayaan"],
  },
  {
    kodeAkun: "4132",
    namaAkun: "Musyarakah",
    jenisPerusahaan: ["pembiayaan"],
  },
  {
    kodeAkun: "4140",
    namaAkun: "Jumlah Pendapatan Bagi Hasil",
    jenisPerusahaan: ["pembiayaan"],
  },
  {
    kodeAkun: "4149",
    namaAkun: "Pendapatan Lainnya dari Penyaluran Dana",
    jenisPerusahaan: ["pembiayaan"],
  },
  {
    kodeAkun: "4150",
    namaAkun: "Jumlah Pendapatan dari Penyaluran Dana",
    jenisPerusahaan: ["pembiayaan"],
  },
  {
    kodeAkun: "4153",
    namaAkun: "Keuntungan (Kerugian) Selisih Kurs Mata Uang Asing",
    jenisPerusahaan: ["properti", "infrastruktur"],
  },
  {
    kodeAkun: "4154",
    namaAkun: "Bagian atas Laba (Rugi) Entitas Asosiasi (Metode Ekuitas)",
    jenisPerusahaan: ["infrastruktur"],
  },
  {
    kodeAkun: "4155",
    namaAkun: "Bagian atas Laba (Rugi) Entitas Ventura Bersama (Metode Ekuitas)",
    jenisPerusahaan: ["infrastruktur"],
  },
  {
    kodeAkun: "4156",
    namaAkun: "Keuntungan (Kerugian) Instrumen Keuangan Derivatif",
    jenisPerusahaan: ["infrastruktur"],
  },
  {
    kodeAkun: "4161",
    namaAkun: "Keuntungan Penjualan Aset selain Persediaan",
    jenisPerusahaan: ["pembiayaan"],
  },
  {
    kodeAkun: "4171",
    namaAkun: "Pendapatan Underwriting Lain – Neto",
    jenisPerusahaan: ["asuransi"],
  },
  {
    kodeAkun: "4199",
    namaAkun: "Pendapatan Usaha Lainnya",
    jenisPerusahaan: [
      "umum",
      "manufaktur",
      "dagang",
      "jasa",
      "asuransi",
      "properti",
      "infrastruktur",
      "sekuritas",
      "pembiayaan",
    ],
  },
  {
    kodeAkun: "4199",
    namaAkun: "Pendapatan Lain",
    jenisPerusahaan: ["bank_konvensional"],
  },
  {
    kodeAkun: "4199",
    namaAkun: "Pendapatan Operasional Lainnya",
    jenisPerusahaan: ["bank_syariah"],
  },
  {
    kodeAkun: "4200",
    namaAkun: "Jumlah Pendapatan Underwriting",
    jenisPerusahaan: ["asuransi"],
  },
  {
    kodeAkun: "4201",
    namaAkun: "Jumlah Pendapatan Usaha",
    jenisPerusahaan: ["sekuritas", "pembiayaan"],
  },
  {
    kodeAkun: "4210",
    namaAkun: "Jumlah Pendapatan Operasional Lain",
    jenisPerusahaan: ["bank_konvensional", "bank_syariah"],
  },
  {
    kodeAkun: "4220",
    namaAkun: "Pendapatan (Beban) Operasional Lain",
    jenisPerusahaan: ["pembiayaan"],
  },
  {
    kodeAkun: "4300",
    namaAkun: "Laba Kotor",
    jenisPerusahaan: ["umum", "manufaktur", "dagang", "jasa", "properti", "infrastruktur"],
  },
  {
    kodeAkun: "4300",
    namaAkun: "Hasil Usaha Investasi",
    jenisPerusahaan: ["dana_pensiun"],
  },
  {
    kodeAkun: "4300",
    namaAkun: "Laba Underwriting",
    jenisPerusahaan: ["asuransi"],
  },
  {
    kodeAkun: "4300",
    namaAkun: "Pendapatan setelah Distribusi Bagi Hasil",
    jenisPerusahaan: ["bank_syariah"],
  },
  {
    kodeAkun: "4400",
    namaAkun: "Laba (Rugi) Operasional Lain – Bersih",
    jenisPerusahaan: ["bank_konvensional"],
  },
  {
    kodeAkun: "4500",
    namaAkun: "Laba (Rugi) Usaha",
    jenisPerusahaan: ["umum", "manufaktur", "dagang", "jasa", "properti"],
  },
  {
    kodeAkun: "4500",
    namaAkun: "Jumlah Laba (Rugi) Operasional",
    jenisPerusahaan: ["bank_syariah"],
  },
  {
    kodeAkun: "4501",
    namaAkun: "Keuntungan Selisih Kurs",
    jenisPerusahaan: [
      "umum",
      "manufaktur",
      "dagang",
      "jasa",
      "properti",
      "infrastruktur",
      "sekuritas",
      "pembiayaan",
    ],
  },
  {
    kodeAkun: "4501",
    namaAkun: "Keuntungan Selisih Kurs Penjabaran",
    jenisPerusahaan: ["bank_syariah"],
  },
  {
    kodeAkun: "4502",
    namaAkun: "Keuntungan Penjualan Aset Tetap dan Inventaris",
    jenisPerusahaan: ["bank_syariah"],
  },
  {
    kodeAkun: "4503",
    namaAkun: "Keuntungan Penjualan Aset Selain Persediaan",
    jenisPerusahaan: ["umum", "manufaktur", "dagang", "jasa", "sekuritas"],
  },
  {
    kodeAkun: "4511",
    namaAkun: "Pendapatan Bunga",
    jenisPerusahaan: [
      "umum",
      "manufaktur",
      "dagang",
      "jasa",
      "properti",
      "infrastruktur",
      "sekuritas",
    ],
  },
  {
    kodeAkun: "4512",
    namaAkun: "Bunga Keterlambatan Iuran",
    jenisPerusahaan: ["dana_pensiun"],
  },
  {
    kodeAkun: "4513",
    namaAkun: "Laba (Rugi) Penjualan Aset Operasional",
    jenisPerusahaan: ["dana_pensiun"],
  },
  {
    kodeAkun: "4514",
    namaAkun: "Laba (Rugi) Penjualan Aset Lain-Lain",
    jenisPerusahaan: ["dana_pensiun"],
  },
  {
    kodeAkun: "4599",
    namaAkun: "Pendapatan Non Usaha Lainnya",
    jenisPerusahaan: [
      "umum",
      "manufaktur",
      "dagang",
      "jasa",
      "properti",
      "infrastruktur",
      "pembiayaan",
    ],
  },
  {
    kodeAkun: "4599",
    namaAkun: "Pendapatan Lain di Luar Investasi dan Operasional",
    jenisPerusahaan: ["dana_pensiun"],
  },
  {
    kodeAkun: "4599",
    namaAkun: "Pendapatan di Luar Usaha Lainnya",
    jenisPerusahaan: ["sekuritas"],
  },
  {
    kodeAkun: "4599",
    namaAkun: "Pendapatan Non Operasional Lainnya",
    jenisPerusahaan: ["bank_syariah"],
  },
  {
    kodeAkun: "4600",
    namaAkun: "Jumlah Pendapatan Non Usaha",
    jenisPerusahaan: ["umum", "manufaktur", "dagang", "jasa", "properti", "infrastruktur"],
  },
  {
    kodeAkun: "4600",
    namaAkun: "Pendapatan Non Operasional",
    jenisPerusahaan: ["bank_konvensional", "asuransi"],
  },
  {
    kodeAkun: "4600",
    namaAkun: "Jumlah Pendapatan di Luar Usaha",
    jenisPerusahaan: ["sekuritas", "pembiayaan"],
  },
  {
    kodeAkun: "4700",
    namaAkun: "Laba (Rugi) Non Usaha",
    jenisPerusahaan: ["umum", "manufaktur", "dagang", "jasa", "properti"],
  },
  {
    kodeAkun: "4700",
    namaAkun: "Laba (Rugi) Non Operasional – Bersih",
    jenisPerusahaan: ["bank_konvensional"],
  },
  {
    kodeAkun: "4700",
    namaAkun: "Jumlah Pendapatan (Beban) Non Operasional",
    jenisPerusahaan: ["dana_pensiun"],
  },
  {
    kodeAkun: "4700",
    namaAkun: "Laba (Rugi) Non Operasional",
    jenisPerusahaan: ["asuransi"],
  },
  {
    kodeAkun: "4700",
    namaAkun: "Jumlah Laba (Rugi) Non Operasional",
    jenisPerusahaan: ["bank_syariah"],
  },
  {
    kodeAkun: "4800",
    namaAkun: "Laba (Rugi) Sebelum Pajak",
    jenisPerusahaan: [
      "umum",
      "manufaktur",
      "dagang",
      "jasa",
      "bank_konvensional",
      "dana_pensiun",
      "asuransi",
      "properti",
      "bank_syariah",
      "infrastruktur",
      "sekuritas",
      "pembiayaan",
    ],
  },
  {
    kodeAkun: "5001",
    namaAkun: "Pembelian",
    jenisPerusahaan: ["umum", "dagang"],
  },
  {
    kodeAkun: "5003",
    namaAkun: "Beban Pengangkutan",
    jenisPerusahaan: ["umum", "dagang"],
  },
  {
    kodeAkun: "5007",
    namaAkun: "Beban Lainnya",
    jenisPerusahaan: ["umum", "dagang"],
  },
  {
    kodeAkun: "5008",
    namaAkun: "Persediaan Awal",
    jenisPerusahaan: ["umum", "dagang"],
  },
  {
    kodeAkun: "5008",
    namaAkun: "Persediaan Awal Barang Jadi",
    jenisPerusahaan: ["manufaktur"],
  },
  {
    kodeAkun: "5009",
    namaAkun: "Dikurangi: Persediaan Akhir",
    jenisPerusahaan: ["umum", "dagang"],
  },
  {
    kodeAkun: "5009",
    namaAkun: "(Persediaan Akhir Barang Jadi)",
    jenisPerusahaan: ["manufaktur"],
  },
  {
    kodeAkun: "5020",
    namaAkun: "Jumlah HPP",
    jenisPerusahaan: ["umum", "manufaktur", "dagang"],
  },
  {
    kodeAkun: "5020",
    namaAkun: "Biaya Pokok Jasa",
    jenisPerusahaan: ["jasa"],
  },
  {
    kodeAkun: "5021",
    namaAkun: "Persediaan Awal Bahan Baku",
    jenisPerusahaan: ["manufaktur"],
  },
  {
    kodeAkun: "5022",
    namaAkun: "Pembelian Bahan Baku",
    jenisPerusahaan: ["manufaktur"],
  },
  {
    kodeAkun: "5029",
    namaAkun: "(Retur Pembelian Bahan Baku)",
    jenisPerusahaan: ["manufaktur"],
  },
  {
    kodeAkun: "5030",
    namaAkun: "Jumlah Pembelian Bahan Baku",
    jenisPerusahaan: ["manufaktur"],
  },
  {
    kodeAkun: "5031",
    namaAkun: "Bahan Baku yang Tersedia untuk Produksi",
    jenisPerusahaan: ["manufaktur"],
  },
  {
    kodeAkun: "5032",
    namaAkun: "(Persediaan Akhir Bahan Baku)",
    jenisPerusahaan: ["manufaktur"],
  },

  { kodeAkun: "5040", namaAkun: "Jumlah Biaya Bahan Baku", jenisPerusahaan: ["manufaktur"] },
  { kodeAkun: "5050", namaAkun: "Biaya Tenaga Kerja Langsung", jenisPerusahaan: ["manufaktur"] },
  {
    kodeAkun: "5051",
    namaAkun: "Biaya Tenaga Kerja Tidak Langsung",
    jenisPerusahaan: ["manufaktur"],
  },
  {
    kodeAkun: "5052",
    namaAkun: "Biaya Pemeliharaan dan Perbaikan Mesin",
    jenisPerusahaan: ["manufaktur"],
  },
  {
    kodeAkun: "5058",
    namaAkun: "Biaya Penyusutan dan Amortisasi",
    jenisPerusahaan: ["manufaktur"],
  },
  { kodeAkun: "5059", namaAkun: "Biaya Utilitas", jenisPerusahaan: ["manufaktur"] },
  {
    kodeAkun: "5069",
    namaAkun: "Biaya Pabrikasi Lainnya (Termasuk Pita Cukai)",
    jenisPerusahaan: ["manufaktur"],
  },
  { kodeAkun: "5070", namaAkun: "Jumlah Biaya Pabrikasi", jenisPerusahaan: ["manufaktur"] },
  { kodeAkun: "5080", namaAkun: "Jumlah Biaya Produksi", jenisPerusahaan: ["manufaktur"] },
  {
    kodeAkun: "5090",
    namaAkun: "Persediaan Awal Barang Dalam Proses",
    jenisPerusahaan: ["manufaktur"],
  },
  {
    kodeAkun: "5099",
    namaAkun: "(Persediaan Akhir Barang Dalam Proses)",
    jenisPerusahaan: ["manufaktur"],
  },
  { kodeAkun: "5100", namaAkun: "Jumlah Harga Pokok Produksi", jenisPerusahaan: ["manufaktur"] },

  { kodeAkun: "5101", namaAkun: "Klaim Bruto", jenisPerusahaan: ["asuransi"] },
  { kodeAkun: "5102", namaAkun: "Klaim Reasuransi", jenisPerusahaan: ["asuransi"] },
  {
    kodeAkun: "5103",
    namaAkun: "Kenaikan (Penurunan) Cadangan Klaim",
    jenisPerusahaan: ["asuransi"],
  },
  { kodeAkun: "5109", namaAkun: "Beban Underwriting Lain - Neto", jenisPerusahaan: ["asuransi"] },
  { kodeAkun: "5200", namaAkun: "Jumlah Beban Underwriting", jenisPerusahaan: ["asuransi"] },

  { kodeAkun: "5201", namaAkun: "Beban Transaksi", jenisPerusahaan: ["dana_pensiun"] },
  {
    kodeAkun: "5202",
    namaAkun: "Beban Pemeliharaan Tanah dan Bangunan",
    jenisPerusahaan: ["dana_pensiun"],
  },
  { kodeAkun: "5203", namaAkun: "Beban Penyusutan Bangunan", jenisPerusahaan: ["dana_pensiun"] },
  { kodeAkun: "5204", namaAkun: "Beban Manajer Investasi", jenisPerusahaan: ["dana_pensiun"] },
  { kodeAkun: "5205", namaAkun: "Beban Kustodi", jenisPerusahaan: ["dana_pensiun", "sekuritas"] },
  { kodeAkun: "5299", namaAkun: "Beban Investasi Lain", jenisPerusahaan: ["dana_pensiun"] },
  { kodeAkun: "5300", namaAkun: "Jumlah Beban Investasi", jenisPerusahaan: ["dana_pensiun"] },

  { kodeAkun: "5301", namaAkun: "Non Profit Sharing", jenisPerusahaan: ["pembiayaan"] },
  { kodeAkun: "5302", namaAkun: "Profit Sharing", jenisPerusahaan: ["pembiayaan"] },
  {
    kodeAkun: "5310",
    namaAkun: "Jumlah Bagi Hasil untuk Pemilik Dana Investasi",
    jenisPerusahaan: ["pembiayaan"],
  },

  {
    kodeAkun: "5311",
    namaAkun: "Gaji, Tunjangan, Bonus, Honorarium, THR, dsb",
    jenisPerusahaan: [
      "umum",
      "manufaktur",
      "dagang",
      "jasa",
      "bank_konvensional",
      "dana_pensiun",
      "asuransi",
      "properti",
      "bank_syariah",
      "infrastruktur",
      "sekuritas",
      "pembiayaan",
    ],
    level: 1,
  },
  {
    kodeAkun: "5312",
    namaAkun: "Beban Imbalan Kerja Lainnya",
    jenisPerusahaan: [
      "umum",
      "manufaktur",
      "dagang",
      "jasa",
      "bank_konvensional",
      "dana_pensiun",
      "asuransi",
      "properti",
      "infrastruktur",
      "sekuritas",
      "pembiayaan",
    ],
    level: 1,
  },
  {
    kodeAkun: "5313",
    namaAkun: "Beban Transportasi",
    jenisPerusahaan: [
      "umum",
      "manufaktur",
      "dagang",
      "jasa",
      "bank_konvensional",
      "asuransi",
      "bank_syariah",
      "infrastruktur",
      "sekuritas",
      "pembiayaan",
    ],
    level: 1,
  },
  {
    kodeAkun: "5314",
    namaAkun: "Beban Penyusutan dan Amortisasi",
    jenisPerusahaan: [
      "umum",
      "manufaktur",
      "dagang",
      "jasa",
      "bank_konvensional",
      "dana_pensiun",
      "asuransi",
      "properti",
      "bank_syariah",
      "infrastruktur",
      "sekuritas",
      "pembiayaan",
    ],
    level: 1,
  },
  {
    kodeAkun: "5315",
    namaAkun: "Beban Sewa",
    jenisPerusahaan: [
      "umum",
      "manufaktur",
      "dagang",
      "jasa",
      "bank_konvensional",
      "asuransi",
      "properti",
      "bank_syariah",
      "infrastruktur",
      "sekuritas",
      "pembiayaan",
    ],
    level: 1,
  },
  {
    kodeAkun: "5316",
    namaAkun: "Beban Bunga",
    jenisPerusahaan: [
      "umum",
      "manufaktur",
      "dagang",
      "jasa",
      "bank_konvensional",
      "dana_pensiun",
      "asuransi",
      "properti",
      "infrastruktur",
      "sekuritas",
      "pembiayaan",
    ],
    level: 1,
  },

  {
    kodeAkun: "5317",
    namaAkun: "Beban Sehubungan dengan Jasa",
    jenisPerusahaan: [
      "umum",
      "manufaktur",
      "dagang",
      "jasa",
      "bank_konvensional",
      "asuransi",
      "properti",
      "infrastruktur",
      "sekuritas",
      "pembiayaan",
    ],
    level: 1,
  },
  {
    kodeAkun: "5317",
    namaAkun: "Beban Jasa Pihak Ketiga",
    jenisPerusahaan: ["dana_pensiun"],
    level: 1,
  },

  {
    kodeAkun: "5318",
    namaAkun: "Beban Penurunan Nilai",
    jenisPerusahaan: [
      "umum",
      "manufaktur",
      "dagang",
      "jasa",
      "bank_konvensional",
      "dana_pensiun",
      "asuransi",
      "properti",
      "infrastruktur",
      "sekuritas",
      "pembiayaan",
    ],
    level: 1,
  },
  {
    kodeAkun: "5319",
    namaAkun: "Beban Royalti",
    jenisPerusahaan: [
      "umum",
      "manufaktur",
      "dagang",
      "jasa",
      "asuransi",
      "properti",
      "infrastruktur",
      "sekuritas",
      "pembiayaan",
    ],
    level: 1,
  },

  {
    kodeAkun: "5320",
    namaAkun: "Beban Pemasaran atau Promosi",
    jenisPerusahaan: [
      "umum",
      "manufaktur",
      "dagang",
      "jasa",
      "bank_konvensional",
      "dana_pensiun",
      "asuransi",
      "properti",
      "bank_syariah",
      "infrastruktur",
      "sekuritas",
      "pembiayaan",
    ],
    level: 1,
  },
  {
    kodeAkun: "5321",
    namaAkun: "Beban Entertainment",
    jenisPerusahaan: [
      "umum",
      "manufaktur",
      "dagang",
      "jasa",
      "bank_konvensional",
      "asuransi",
      "properti",
      "bank_syariah",
      "infrastruktur",
      "sekuritas",
      "pembiayaan",
    ],
    level: 1,
  },
  {
    kodeAkun: "5322",
    namaAkun: "Beban Umum dan Administrasi",
    jenisPerusahaan: [
      "umum",
      "manufaktur",
      "dagang",
      "bank_konvensional",
      "properti",
      "infrastruktur",
      "sekuritas",
      "pembiayaan",
    ],
    level: 1,
  },
  { kodeAkun: "5323", namaAkun: "Beban Kantor", jenisPerusahaan: ["dana_pensiun"], level: 1 },
  {
    kodeAkun: "5324",
    namaAkun: "Beban Penjualan",
    jenisPerusahaan: ["properti", "infrastruktur"],
    level: 1,
  },
  {
    kodeAkun: "5325",
    namaAkun: "Beban Interkoreksi",
    jenisPerusahaan: ["infrastruktur"],
    level: 1,
  },
  {
    kodeAkun: "5326",
    namaAkun: "Beban Pemeliharaan dan Perbaikan",
    jenisPerusahaan: ["dana_pensiun", "pembiayaan"],
    level: 1,
  },
  { kodeAkun: "5327", namaAkun: "Beban Premi Asuransi", jenisPerusahaan: ["pembiayaan"], level: 1 },
  {
    kodeAkun: "5328",
    namaAkun: "Beban Premi atas Transaksi Swap",
    jenisPerusahaan: ["pembiayaan"],
    level: 1,
  },

  { kodeAkun: "5341", namaAkun: "Beban Bonus Wadiah", jenisPerusahaan: ["pembiayaan"], level: 1 },
  {
    kodeAkun: "5342",
    namaAkun: "Kerugian dari Penurunan Nilai Wajar Aset Keuangan",
    jenisPerusahaan: ["pembiayaan"],
  },
  {
    kodeAkun: "5343",
    namaAkun: "Kerugian Penjualan Aset (Surat Berharga dan Ijarah)",
    jenisPerusahaan: ["pembiayaan"],
  },
  {
    kodeAkun: "5344",
    namaAkun: "Kerugian Transaksi Spot dan Forward (Realized)",
    jenisPerusahaan: ["pembiayaan"],
  },
  {
    kodeAkun: "5345",
    namaAkun: "Kerugian Penurunan Nilai Aset Keuangan (Impairment)",
    jenisPerusahaan: ["pembiayaan"],
  },

  {
    kodeAkun: "5346",
    namaAkun: "Kerugian Terkait Risiko Operasional",
    jenisPerusahaan: ["bank_konvensional", "bank_syariah"],
  },
  {
    kodeAkun: "5347",
    namaAkun: "Kerugian dari Penyertaan dengan Equity Method",
    jenisPerusahaan: ["pembiayaan"],
  },
  {
    kodeAkun: "5348",
    namaAkun: "Komisi/Provisi/Fee dan Administrasi",
    jenisPerusahaan: ["bank_konvensional", "bank_syariah"],
  },
  {
    kodeAkun: "5349",
    namaAkun: "Kerugian Penurunan Nilai Aset Lainnya (Non Keuangan)",
    jenisPerusahaan: ["pembiayaan"],
  },

  {
    kodeAkun: "5350",
    namaAkun: "Penurunan Nilai Wajar Aset Keuangan",
    jenisPerusahaan: ["bank_konvensional"],
  },
  {
    kodeAkun: "5351",
    namaAkun: "Peningkatan Nilai Wajar Liabilitas Keuangan",
    jenisPerusahaan: ["bank_konvensional"],
  },
  {
    kodeAkun: "5352",
    namaAkun: "Kerugian atas Penjualan Aset Keuangan",
    jenisPerusahaan: ["bank_konvensional"],
  },
  {
    kodeAkun: "5353",
    namaAkun: "Kerugian Transaksi Spot dan Derivatif",
    jenisPerusahaan: ["bank_konvensional"],
  },
  {
    kodeAkun: "5354",
    namaAkun: "Kerugian Penurunan Nilai Aset Keuangan",
    jenisPerusahaan: ["bank_konvensional"],
  },
  {
    kodeAkun: "5356",
    namaAkun: "Kerugian dari Penyertaan dengan Equity Method",
    jenisPerusahaan: ["bank_konvensional"],
  },
  {
    kodeAkun: "5358",
    namaAkun: "Kerugian Penurunan Nilai Aset Lainnya (Non Keuangan)",
    jenisPerusahaan: ["bank_konvensional"],
  },

  {
    kodeAkun: "5399",
    namaAkun: "Beban Usaha Lainnya",
    jenisPerusahaan: [
      "umum",
      "manufaktur",
      "dagang",
      "jasa",
      "bank_konvensional",
      "properti",
      "infrastruktur",
      "sekuritas",
      "pembiayaan",
    ],
    level: 1,
  },
  {
    kodeAkun: "5399",
    namaAkun: "Beban Operasional Lainnya",
    jenisPerusahaan: ["dana_pensiun", "asuransi", "bank_syariah"],
  },

  {
    kodeAkun: "5400",
    namaAkun: "Jumlah Beban Usaha",
    jenisPerusahaan: [
      "umum",
      "manufaktur",
      "dagang",
      "jasa",
      "properti",
      "infrastruktur",
      "sekuritas",
      "pembiayaan",
    ],
  },
  {
    kodeAkun: "5400",
    namaAkun: "Jumlah Beban Operasional",
    jenisPerusahaan: ["dana_pensiun", "asuransi"],
  },

  {
    kodeAkun: "5401",
    namaAkun: "Total Beban Operasional Lain",
    jenisPerusahaan: ["bank_konvensional"],
  },
  {
    kodeAkun: "5401",
    namaAkun: "Jumlah Beban Operasional Lain",
    jenisPerusahaan: ["bank_syariah"],
  },

  {
    kodeAkun: "5405",
    namaAkun: "Kerugian Penjualan Aset selain Persediaan",
    jenisPerusahaan: [
      "umum",
      "manufaktur",
      "dagang",
      "jasa",
      "properti",
      "infrastruktur",
      "sekuritas",
      "pembiayaan",
    ],
    level: 1,
  },
  {
    kodeAkun: "5409",
    namaAkun: "Sumbangan",
    jenisPerusahaan: [
      "umum",
      "manufaktur",
      "dagang",
      "jasa",
      "properti",
      "infrastruktur",
      "sekuritas",
      "pembiayaan",
    ],
    level: 1,
  },
  {
    kodeAkun: "5421",
    namaAkun: "Kerugian Selisih Kurs",
    jenisPerusahaan: [
      "umum",
      "manufaktur",
      "dagang",
      "jasa",
      "properti",
      "bank_syariah",
      "infrastruktur",
      "sekuritas",
      "pembiayaan",
    ],
    level: 1,
  },
  {
    kodeAkun: "5421",
    namaAkun: "Kerugian Selisih Kurs Penjabaran",
    jenisPerusahaan: ["bank_syariah"],
  },
  {
    kodeAkun: "5422",
    namaAkun: "Kerugian Penjualan Aset Tetap dan Inventaris",
    jenisPerusahaan: ["pembiayaan"],
  },

  {
    kodeAkun: "5499",
    namaAkun: "Beban Non Usaha Lainnya",
    jenisPerusahaan: ["umum", "manufaktur", "dagang", "jasa", "properti", "infrastruktur"],
    level: 1,
  },
  {
    kodeAkun: "5499",
    namaAkun: "Beban Lain di Luar Investasi dan Operasional",
    jenisPerusahaan: ["dana_pensiun"],
    level: 1,
  },
  {
    kodeAkun: "5499",
    namaAkun: "Beban Non Operasional Lainnya",
    jenisPerusahaan: ["bank_syariah"],
    level: 1,
  },
  {
    kodeAkun: "5499",
    namaAkun: "Beban di Luar Usaha Lainnya",
    jenisPerusahaan: ["sekuritas", "pembiayaan"],
    level: 1,
  },

  {
    kodeAkun: "5500",
    namaAkun: "Jumlah Beban Non Usaha",
    jenisPerusahaan: ["umum", "manufaktur", "dagang", "jasa", "properti", "infrastruktur"],
    level: 1,
  },
  {
    kodeAkun: "5500",
    namaAkun: "Beban Non Operasional",
    jenisPerusahaan: ["bank_konvensional", "asuransi"],
    levvel: 1,
  },
  {
    kodeAkun: "5500",
    namaAkun: "Jumlah Beban di Luar Usaha",
    jenisPerusahaan: ["sekuritas", "pembiayaan"],
    level: 1,
  },

  // //  AKUN UMUM (BERLAKU UNTUK SEMUA)
  // {
  //   kodeAkun: "4003",
  //   namaAkun: "Penjualan Ekspor",
  // },
  // {
  //   kodeAkun: "4011",
  //   namaAkun: "Retur",
  // },
];
