import React, { useState } from "react";
import LaporanLabaRugi from "./LaporanLabaRugi";
import ModalLabaRugi from "@lampiran/Lampiran3/LaporanLabaRugi/form/ModalLabaRugi";
import { buildSchema } from "@lampiran/Lampiran3/LaporanLabaRugi/form/schemas";

// 👉 ROWS PATEN: isi lengkap sesuai yang dipingin bang pusing pala aing
const ROWS = [
    // =======================
    // GROUP: PENJUALAN
    // =======================
    { id: "g-penjualan", type: "header", level: 0, keterangan: "Penjualan" },

    {
        id: 4002,
        kodeAkun: "4002",
        keterangan: "Domestik",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 4003,
        kodeAkun: "4003",
        keterangan: "Ekspor",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },

    // 4004: Penjualan Kotor (Gross Sales)
    { id: 4004, kodeAkun: "4004", keterangan: "Penjualan Kotor", type: "subtotal", level: 0 },

    // DIKURANGI:
    { id: "label-dikurangi1", type: "label", level: 0, keterangan: "Dikurangi :" },
    {
        id: 4011,
        kodeAkun: "4011",
        keterangan: "Pengembalian",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 4012,
        kodeAkun: "4012",
        keterangan: "Potongan Penjualan",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 4013,
        kodeAkun: "4013",
        keterangan: "Penyesuaian Penjualan",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },

    // 4020: Penjualan Bersih (Net Sales)
    { id: 4020, kodeAkun: "4020", keterangan: "Penjualan Bersih", type: "subtotal", level: 0 },

    // =======================
    // GROUP: HARGA POKOK PRODUKSI / HPP
    // (disusun mengikuti struktur di gambar)
    // =======================
    { id: "g-hpp-prod", type: "header", level: 0, keterangan: "Harga Pokok Produksi" },

    // Biaya Bahan Baku
    { id: "label-bbb", type: "label", level: 0, keterangan: "Biaya Bahan Baku:" },
    {
        id: 5021,
        kodeAkun: "5021",
        keterangan: "Persediaan Awal Bahan Baku",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 5022,
        kodeAkun: "5022",
        keterangan: "Pembelian Bahan Baku",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 5029,
        kodeAkun: "5029",
        keterangan: "Dikurangi: Retur Pembelian",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 5030,
        kodeAkun: "5030",
        keterangan: "Total Pembelian Bahan Baku",
        type: "subtotal",
        level: 1,
    },
    {
        id: 5031,
        kodeAkun: "5031",
        keterangan: "Persediaan Bahan Baku Tersedia untuk Produksi",
        type: "subtotal",
        level: 1,
    },
    {
        id: 5032,
        kodeAkun: "5032",
        keterangan: "Dikurangi: Persediaan Akhir Bahan Baku",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    { id: 5040, kodeAkun: "5040", keterangan: "Total Biaya Bahan Baku", type: "subtotal", level: 0 },

    // Tenaga Kerja Langsung
    {
        id: 5050,
        kodeAkun: "5050",
        keterangan: "Biaya Tenaga Kerja Langsung",
        type: "line",
        level: 0,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },

    // Biaya Pabrikasi (Overhead)
    { id: "g-overhead", type: "label", level: 0, keterangan: "Biaya Pabrikasi" },
    {
        id: 5051,
        kodeAkun: "5051",
        keterangan: "Biaya Tenaga Kerja Tidak Langsung",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 5052,
        kodeAkun: "5052",
        keterangan: "Biaya Perbaikan & Pemeliharaan Mesin",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 5058,
        kodeAkun: "5058",
        keterangan: "Penyusutan & Amortisasi",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 5069,
        kodeAkun: "5069",
        keterangan: "Biaya Overhead Lainnya",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    { id: 5070, kodeAkun: "5070", keterangan: "Total Biaya Overhead Pabrik", type: "subtotal", level: 0 },

    { id: 5080, kodeAkun: "5080", keterangan: "Total Biaya Produksi", type: "subtotal", level: 0 },

    {
        id: 5090,
        kodeAkun: "5090",
        keterangan: "Persediaan Awal Barang Dalam Proses",
        type: "line",
        level: 0,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 5099,
        kodeAkun: "5099",
        keterangan: "Dikurangi: Persediaan Akhir Barang Dalam Proses",
        type: "line",
        level: 0,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    { id: 5100, kodeAkun: "5100", keterangan: "Total Biaya Barang yang Diproduksi", type: "subtotal", level: 0 },

    // Rekap HPP (COGS)
    {
        id: 5008,
        kodeAkun: "5008",
        keterangan: "Persediaan Awal Barang Jadi",
        type: "line",
        level: 0,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 5009,
        kodeAkun: "5009",
        keterangan: "Persediaan Akhir Barang Jadi",
        type: "line",
        level: 0,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },

    // 5020: Total HPP (COGS)
    { id: 5020, kodeAkun: "5020", keterangan: "Jumlah HPP (Harga Pokok Penjualan)", type: "subtotal", level: 0 },

    // 4300: Laba Kotor
    { id: 4300, kodeAkun: "4300", keterangan: "Laba Kotor", type: "subtotal", level: 0 },

    // =======================
    // BEBAN OPERASIONAL
    // =======================
    { id: "g-beban-opr", type: "header", level: 0, keterangan: "Beban Operasional" },
    {
        id: 5311,
        kodeAkun: "5311",
        keterangan: "Gaji, Upah, Bonus, Tunjangan",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 5312,
        kodeAkun: "5312",
        keterangan: "Beban Manfaat Karyawan Lainnya",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 5313,
        kodeAkun: "5313",
        keterangan: "Beban Transportasi",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 5314,
        kodeAkun: "5314",
        keterangan: "Beban Penyusutan & Amortisasi",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 5315,
        kodeAkun: "5315",
        keterangan: "Beban Sewa",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 5316,
        kodeAkun: "5316",
        keterangan: "Beban Bunga",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 5317,
        kodeAkun: "5317",
        keterangan: "Beban Terkait Jasa",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 5318,
        kodeAkun: "5318",
        keterangan: "Beban Penurunan Nilai",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 5319,
        kodeAkun: "5319",
        keterangan: "Beban Royalti",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 5320,
        kodeAkun: "5320",
        keterangan: "Beban Pemasaran/Promosi",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 5321,
        kodeAkun: "5321",
        keterangan: "Beban Hiburan",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 5322,
        kodeAkun: "5322",
        keterangan: "Beban Umum & Administrasi",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 5399,
        kodeAkun: "5399",
        keterangan: "Beban Operasional Lainnya",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },

    // 5400: Total Operasional
    { id: 5400, kodeAkun: "5400", keterangan: "Total Operasional", type: "subtotal", level: 0 },

    // 4500: Laba (Rugi) Operasional
    { id: 4500, kodeAkun: "4500", keterangan: "Laba (Rugi) Operasional", type: "subtotal", level: 0 },

    // =======================
    // PENDAPATAN NON USAHA
    // =======================
    { id: "g-pend-nonusaha", type: "header", level: 0, keterangan: "Pendapatan Non Usaha" },
    {
        id: 4501,
        kodeAkun: "4501",
        keterangan: "Keuntungan Selisih Kurs",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 4503,
        kodeAkun: "4503",
        keterangan: "Keuntungan Penjualan Aset Selain Persediaan",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 4511,
        kodeAkun: "4511",
        keterangan: "Pendapatan Bunga (termasuk giro & bunga efektif)",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 4599,
        kodeAkun: "4599",
        keterangan: "Pendapatan Non-Operasional Lainnya",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },

    // 4600: Total Pendapatan Non-Operasional
    { id: 4600, kodeAkun: "4600", keterangan: "Total Pendapatan Non-Operasional", type: "subtotal", level: 0 },

    // =======================
    // BEBAN NON USAHA
    // =======================
    { id: "g-beban-nonusaha", type: "header", level: 0, keterangan: "Beban Non Usaha" },
    {
        id: 5405,
        kodeAkun: "5405",
        keterangan: "Kerugian Penjualan Aset Selain Persediaan",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 5409,
        kodeAkun: "5409",
        keterangan: "Sumbangan",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 5421,
        kodeAkun: "5421",
        keterangan: "Kerugian Selisih Kurs",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    {
        id: 5499,
        kodeAkun: "5499",
        keterangan: "Beban Non-Operasional Lainnya",
        type: "line",
        level: 1,
        nilaiKomersial: 0,
        nonObjekPajak: 0,
        pphFinal: 0,
        tidakFinal: 0,
        penyesuaianPositif: 0,
        penyesuaianNegatif: 0,
        kodePenyesuaian: "",
        nilaiFiskal: 0,
    },
    { id: 5500, kodeAkun: "5500", keterangan: "Total Beban Non-Operasional", type: "subtotal", level: 0 },

    // Ringkasan non-operasional & sebelum pajak
    { id: 4700, kodeAkun: "4700", keterangan: "Laba (Rugi) Non-Operasional", type: "subtotal", level: 0 },
    { id: 4800, kodeAkun: "4800", keterangan: "Laba (Rugi) Sebelum Pajak", type: "subtotal", level: 0 },
];

export default function Lampiran3A1() {
    const [rows, setRows] = useState(ROWS);
    const [open, setOpen] = useState(false);
    const [schema, setSchema] = useState([]);
    const [selected, setSelected] = useState(null);

    const openModal = (row) => {
        // untuk header/label/subtotal → lock semua field (tidak bisa edit) Keseleuruhan King kalo ini
        const isReadOnlyRow = row.type !== "line";
        const dyn = isReadOnlyRow
            ? [
                { name: "kodeAkun", readOnly: true },
                { name: "keterangan", readOnly: true },
                { name: "nilaiKomersial", readOnly: true },
                { name: "nonObjekPajak", readOnly: true },
                { name: "pphFinal", readOnly: true },
                { name: "tidakFinal", readOnly: true },
                { name: "penyesuaianPositif", readOnly: true },
                { name: "penyesuaianNegatif", readOnly: true },
                { name: "kodePenyesuaian", readOnly: true },
                { name: "nilaiFiskal", readOnly: true },
            ]
            : [
                // contoh: untuk baris angka tetap, identitas dikunci( Untuk baris biasa, Tetapi buat semuanya)
                { name: "kodeAkun", readOnly: true },
                { name: "keterangan", readOnly: true },
                { name: "nilaiFiskal", readOnly: true },
            ];

        setSchema(buildSchema(row, dyn));
        setSelected(row);
        setOpen(true);
    };

    const closeModal = () => {
        setOpen(false);
        setSelected(null);
    };

    const onSubmit = (values) => {
        console.log(">>> submit dari modal", values);
        setRows((prev) => prev.map((r) => (r.id === selected.id ? { ...r, ...values } : r)));
        closeModal();
    };


    return (
        <>
            <LaporanLabaRugi rows={rows} openModal={openModal} />
            <ModalLabaRugi
                open={open}
                onClose={closeModal}
                title={selected ? "UBAH" : "UBAH"}
                schema={schema}
                initialData={selected || {}}
                onSubmit={onSubmit}
            />
        </>
    );
}
