export { default as KasdanSetaraKas } from "./Lampiran1/BagianA/KasdanSetarakas"; 
export { default as Piutang } from "./Lampiran1/BagianA/Piutang";
export { default as Investasi } from "./Lampiran1/BagianA/Investasi";
export { default as HartaBergerak } from "./Lampiran1/BagianA/HartaBergerak";
export { default as HartaTidakBergerak } from "./Lampiran1/BagianA/HartaTidakBergerak";
export { default as HartaLainnya } from "./Lampiran1/BagianA/HartaLainnya";
export { default as Ikhtisar } from "./Lampiran1/BagianA/Ikhtisar";
export {default as UtangAkhir} from "./Lampiran1/BagianB/UtangAkhir";
export {default as Penghasilan} from "./Lampiran1/BagianD/Penghasilan";
export {default as Pemotongan} from "./Lampiran1/BagianE/Pemotongan";
